FreshEveryDay/dailyfresh-master/dailyfresh-master/cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^addcart', views.add_cart, name='add_cart'),
    url(r'^updatecart', views.update_cart, name='update_cart'),
    url(r'^delete', views.delete, name='delete'),
    url(r'^$', views.cart, name='cart')
]

FreshEveryDay/dailyfresh-master/dailyfresh-master/dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from product.views import home
from dailyfresh.settings import BASE_DIR
from django.shortcuts import render


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^$', home, name='home'),
]

FreshEveryDay/dailyfresh-master/dailyfresh-master/product/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'index/$', views.home, name='home'),
    url(r'detail/(?P<sku_id>\d+)$', views.detail, name='detail'),
    url(r'list/(?P<type>\d+)/(?P<page_num>\d+)/$', views.list, name='list'),
    # url(r'$', views.home, name='home'),
]

FreshEveryDay/dailyfresh-master/dailyfresh-master/user/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^register/checkname/(?P<name>\w+)$', views.check_name, name='checkname'),
    url(r'^register/active/(?P<token>.*)$', views.active_acount, name='active'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.tt_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^userinfo/$', views.user_info, name='userinfo'),
    url(r'^userorder/(\w+)$', views.user_order, name='userorder'),
    url(r'^useraddress', views.useraddress, name='useraddress'),
    # url(r'^useraddress', views.useraddress, name='useraddress'),
]

FreshEveryDay/dailyfresh-master/dailyfresh-master/product/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField


class ProductCategory(BaseModel):
    '''商品类型类'''
    category_name = models.CharField(max_length=20, verbose_name='分类名称')
    logo = models.CharField(max_length=10, verbose_name='标识')
    image = models.ImageField(upload_to='category', verbose_name='商品类型图片')

    class Meta:
        db_table = 'product_category'
        verbose_name = '商品分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category_name


class Products(BaseModel):
    '''商品SPU模型类'''
    name = models.CharField(max_length=20, verbose_name='商品SPU名称')
    detail = HTMLField(blank=True, verbose_name='商品详情')

    class Meta:
        db_table = 'products'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class ProductSKU(BaseModel):
    PRODUCT_STATUS = (
        (0, '下线'),
        (1, '上线')
    )
    name = models.CharField(max_length=50, verbose_name='商品名称')
    desc = models.CharField(max_length=100, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unite = models.CharField(max_length=20, verbose_name='单位')
    image = models.ImageField(upload_to='products', verbose_name='商品图片')
    inventory = models.IntegerField(default=1, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    status = models.SmallIntegerField(default=1,choices=PRODUCT_STATUS, verbose_name='商品状态')
    type = models.ForeignKey(ProductCategory, verbose_name='所属分类')
    products = models.ForeignKey(Products, verbose_name='商品SPU')

    class Meta:
        db_table = 'product_sku'
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class ProductImage(BaseModel):
    image = models.ImageField(upload_to='products', verbose_name='商品图片路径')
    product = models.ForeignKey(ProductSKU, verbose_name='商品')

    class Meta:
        db_table = 'product_image'
        verbose_name = '商品图片'
        verbose_name_plural = verbose_name


class ProductBanner(BaseModel):
    image = models.ImageField(upload_to='banner', verbose_name='轮播图片')
    index = models.SmallIntegerField(default=0, verbose_name='轮播索引')
    product = models.ForeignKey(ProductSKU, verbose_name='商品')

    class Meta:
        db_table = 'product_banner'
        verbose_name = '首页轮播商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.product.name


class PromotionPc(BaseModel):
    name = models.CharField(max_length=20, verbose_name='活动名称')
    image = models.ImageField(upload_to='banner', verbose_name='活动图片')
    url = models.URLField(verbose_name='互动连接')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'promotion'
        verbose_name = '促销活动'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class TypeShow(BaseModel):
    DISPLAY_TYPE_CHOICES = (
        (0, '文字'),
        (1, '图片')
    )
    display_type = models.SmallIntegerField(choices=DISPLAY_TYPE_CHOICES, default=1, verbose_name='展示类型')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')
    product = models.ForeignKey(ProductSKU, verbose_name='商品SKU')
    product_type = models.ForeignKey(ProductCategory, verbose_name='商品种类')

    class Meta:
        db_table = 'product_show'
        verbose_name = '分类商品展示'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.product_type.category_name

FreshEveryDay/dailyfresh-master/dailyfresh-master/product/views.py
from django.shortcuts import render, HttpResponse
from .models import ProductCategory, ProductBanner, PromotionPc, TypeShow, Products
from django_redis import get_redis_connection
from django.core.cache import cache
from product.models import ProductSKU
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import JsonResponse

def home(request):
    context = cache.get('index_page_cache')
    if context is None:
        print('没有缓存')
        types = ProductCategory.objects.all()
        banners = ProductBanner.objects.all().order_by('index')
        promotion = PromotionPc.objects.all().order_by('index')
        for type in types:
            word_show = TypeShow.objects.filter(product_type=type, display_type=0).order_by('index')
            pic_show = TypeShow.objects.filter(product_type=type, display_type=1).order_by('index')
            type.word_show = word_show
            type.pic_show = pic_show
        context = {
                'types': types,
                'banners': banners,
                'promotion': promotion,
            }
        # 设置缓存
        cache.set('index_page_cache', context)
    user = request.user
    if user.is_authenticated():
        cart_key = 'cart_%d' % user.id
        con = get_redis_connection('default')
        cart_count = con.hlen(cart_key)
        context['cart_count'] = cart_count
    return render(request, 'products/home.html', context)


def detail(request, sku_id):
    types = ProductCategory.objects.all()
    try:
        product = ProductSKU.objects.get(id=sku_id)
    except ProductSKU.DoesNotExist:
        return HttpResponse('访问页面不存在')
    new_products = ProductSKU.objects.filter(type=product.type).order_by('-update_date')[:2]
    same_spu_products = ProductSKU.objects.filter(products=product.products).exclude(id=sku_id)
    context = {
        'product': product,
        'types': types,
        'new_products': new_products,
        'same_spu_products': same_spu_products,
    }
    user = request.user
    if user.is_authenticated():
        cart_key = 'cart_%d' % user.id
        history_key = 'history_%user' % user.id
        con = get_redis_connection('default')
        con.lrem(history_key, 0, sku_id)
        con.lpush(history_key, sku_id)
        con.ltrim(history_key, 0, 4)
        cart_count = con.hlen(cart_key)
        context['cart_count'] = cart_count
    return render(request, 'products/detail.html', context)


def list(request, type, page_num):
    user = request.user
    sort = request.GET.get('sort', 'default')
    try:
        page_num = int(page_num)
    except Exception:
        page_num = 1
    types = ProductCategory.objects.all()
    type = ProductCategory.objects.get(id=type)
    if sort == 'price':
        skus = ProductSKU.objects.filter(type=type).order_by('price')
    elif sort == 'sales':
        skus = ProductSKU.objects.filter(type=type).order_by('-sales')
    else:
        skus = ProductSKU.objects.filter(type=type)

    page_manage = Paginator(skus, 1)

    try:
        page = page_manage.page(page_num)
    except EmptyPage:
        page = page_manage.page(1)
    new_products = ProductSKU.objects.filter(type=type).order_by('-update_date')[:2]
    # 控制页码显示5页
    total_page_num = page_manage.num_pages
    if total_page_num<5:
        show_nums = range(1, total_page_num+1)
    elif page_num<=3:
        show_nums = range(1,6)
    elif total_page_num-page_num <= 2:
        show_nums = range(page_num-4, total_page_num+1)
    else:
        show_nums = range(page_num-2, page_num+3)
    # show_nums = range(10)
    if user.is_authenticated():
        cart_key = 'cart_%d' % user.id
        con = get_redis_connection('default')
        cart_count = con.hlen(cart_key)
    else:
        cart_count = 0
    context = {
        'types': types,
        'page': page,
        'new_products': new_products,
        'current_type': type,
        'sort': sort,
        'show_nums': show_nums,
        'cart_count': cart_count,
    }
    return render(request, 'products/list.html', context)

FreshEveryDay/dailyfresh-master/dailyfresh-master/templates/products/detail.html
{% extends 'products/p_base.html' %}
{% block title %}
    详情页
{% endblock %}
{% block detail %}
	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ product.image }}"></div>

		<div class="goods_detail_list fr" data-id="{{ product.id }}">
			<h3>{{product.name}}</h3>
			<p>{{product.desc}}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="gprice">{{product.price}}</em></span>
				<span class="show_unit">单  位：{{product.unite}}</span>
			</div>
			<div id="genghuan">
                <div class="goods_num clearfix">
                    <div class="num_name fl">数 量：</div>
                    <div class="num_add fl">
                        <input type="text" class="num_show fl" value="1" id="num_show">
                        <a href="javascript:;" class="add fr" id="add">+</a>
                        <a href="javascript:;" class="minus fr" id="minus">-</a>
                    </div>
                    <div style="margin-left: 350px;line-height: 53px;overflow: hidden;">
                        <div style="width: 77px;height: 52px; float: left">库 存：</div>
                        <div style="border: 1px solid #dddddd;width: 77px;height: 52px;text-align: center;line-height: 53px;
                                overflow: hidden;font-size: 20px;" id="kucun">{{ product.inventory }}</div>
                    </div>
                </div>
                <div>
                    <div>规格:</div>
                        <ul>
                            {% for standard in same_spu_products %}
                                <li><a href="{% url 'product:detail' standard.id%}">{{ standard.unite }}</a></li>
                            {% endfor %}
                        </ul>

                </div>
                <div class="total">总价：<em id="gtotal"></em></div>
                <div class="operate_btn">
                {% csrf_token %}
                    {% if request.user %}
                        <a href="javascript:;" class="buy_btn" id="buy">立即购买</a>
                    {% else %}
                        <a href="/user/login/" class="buy_btn" id="buy">立即购买</a>
                    {% endif %}
                    {% if request.user %}
                        <a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
                    {% else %}
                        <a href="/user/login/" class="add_cart" id="add_cart">加入购物车</a>
                    {% endif %}
                </div>
            </div>
		</div>
	</div>
{% endblock detail%}

{% block list %}
		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{product.products.detail|safe}}</dd>
				</dl>
			</div>

		</div>
{% endblock list %}
{% block js %}
    <script>
        $(function(){
            $('#add').click(function () {
                var value = parseInt($('#num_show').val())
                var inventory = parseInt($('#kucun').text())
                {#alert(inventory)#}
                if(value>=inventory){
                    $('#num_show').val(value)
                    cal_price()
                    return;
                }
                value += 1
                $('#num_show').val(value)
                cal_price()
            });
            $('#num_show').blur(function () {
                let count = parseInt($('#num_show').val())
                if(isNaN(count)||count<=0){
                    $('#num_show').val(1)
                }
            })
            $('#minus').click(function () {
                var value = parseInt($('#num_show').val())
                if(value<=0){
                    return;
                }
                value -= 1
                $('#num_show').val(value)
                cal_price()
            });
            cal_price()
            $('#add_cart').click(function () {
                sku_id = $('.goods_detail_list').attr('data-id')
                count = $('#num_show').val()
                csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val()
                params = {sku_id, count, csrfmiddlewaretoken}

                $.post('/cart/addcart', params, function (data) {
                    if(data.status == 5){
                        $('#show_count').text(data.total_count)
                        {#alert('successful')#}
                    }
                    else{
                        alert(data.msg)
                    }

                })
            })
        })
        function cal_price() {
            single_price = $('#gprice').text()
            count = $('#num_show').val()
            total_price = parseFloat(single_price) * parseInt(count)
            $('#gtotal').text(total_price.toFixed(2)+'元')
        }

    </script>

{% endblock %}

FreshEveryDay/dailyfresh-master/dailyfresh-master/templates/products/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    主页
{% endblock %}
{% block header %}
    <div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            {% if user.is_authenticated%}
             <div class="user_link fl">
                <a href="{% url 'user:userinfo'%}">欢迎您：{{user.username}}</a>
                <span>|</span>
                 <a href="{% url 'user:logout' %}">退出</a>
                <span>|</span>
                <a href="{% url 'user:userinfo' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:cart' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'user:userorder' 1 %}">我的订单</a>
            </div>
            {% else %}
            <div class="login_btn fl">
                <a href="{% url 'user:login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'user:register' %}">注册</a>
            </div>
            {% endif %}

        </div>
    </div>
</div>
<div class="search_bar clearfix">
    <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
    <form method='get' action="/search/" target="_blank">
    <div class="search_con fl">
        <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
        <input type="submit" class="input_btn fr" name="" value="搜索">
    </div>
    </form>


    {% if user.is_authenticated %}
  <div class="guest_cart fr">
        <a href="/cart/" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
    </div>
        {% else %}
        <div class="guest_cart fr">
            <a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
        </div>
    {% endif %}
</div>
{% endblock %}
{% block main %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="#">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="#">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.category_name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for c_img in banners %}
				<li><img src="{{ c_img.image }}" alt="幻灯片"></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for p in promotion %}
			<a href="#"><img src="{{ p.image }}"></a>
{#			<a href="#"><img src="/static/images/adv02.jpg"></a>#}
            {% endfor %}
		</div>
	</div>
    {% for c in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ c.category_name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{%for p in c.word_show%}
				<a href="{% url 'product:detail' p.product.id%}">{{p.product.name|slice:'10'}}...</a>
				{%endfor%}
			</div>
			<a href="{% url 'product:list' c.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ c.image }}"></div>
			<ul class="goods_list fl">
				{%for pic_p in c.pic_show%}
				<li>
					<!--images/goods/goods003.jpg-->
					<h4><a href="{% url 'product:detail' pic_p.product.id%}">{{pic_p.product.name|slice:'10'}}...</a></h4>
					<a href="{% url 'product:detail' pic_p.product.id%}"><img src="{{pic_p.product.image}}"></a>
					<div class="prize">¥{{pic_p.product.price}}</div>
				</li>
				{%endfor%}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock %}
{% block js%}
    <script src="{% static 'product/slide.js' %}"></script>
    <script type="text/javascript">
{#		BCSlideshow('focuspic');#}
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(d){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

FreshEveryDay/dailyfresh-master/dailyfresh-master/templates/products/list.html
{%extends 'products/p_base.html'%}
{% block title%}
    列表页
{% endblock %}
{% block list %}
<div class="r_wrap fr clearfix">
    <div class="sort_bar">
        <a href="{% url 'product:list' current_type.id page.number %}?sort=default"
           {%if sort == "default"%}
        class="active"
        {%endif%}
        >默认</a>
        <a href="{% url 'product:list' current_type.id page.number %}?sort=price"
           {%if sort == "price"%}
        class="active"
        {%endif%}
        >价格</a>
        <a href="{% url 'product:list' current_type.id page.number %}?sort=sales"
           {%if sort == "sales"%}
        class="active"
        {%endif%}
        >人气</a>
    </div>
    <ul class="goods_type_list clearfix">
        {%for p in page.object_list%}
        <li>
            <a href="{% url 'product:detail' p.id %}"><img src="{{ p.image }}"></a>
            <h4><a href="{% url 'product:detail' p.id %}">{{p.name}}</a></h4>
            <div class="operate">
                <span class="prize">￥{{p.price}}</span>
                <span class="unit">{{p.unite}}</span>
                <span class="unit">销量{{p.sales}}</span>
                {% if user.is_authenticated %}
					<a href="javascript:;" id="{{ g.id }}" class="add_goods" title="加入购物车"></a>
				{% else %}
      				<a href="/user/login/" class="add_goods" title="加入购物车"></a>
				{% endif %}
            </div>
        </li>
        {%endfor%}
    </ul>

    <div class="pagenation">
        {% if page.has_previous %}
        <a href="{% url 'product:list' current_type.id page.previous_page_number %}?sort={{ sort }}">上一页</a>
        {% endif %}
        {%for pindex in show_nums%}
        <!--如果选择的是当前页，则标记为活动样式-->
        {%if pindex == page.number%}
        <a href="#" class="active">{{pindex}}</a>
        {%else%}
        <a href="{% url 'product:list' current_type.id pindex %}?sort={{ sort }}">{{pindex}}</a>
        {%endif%}
        {%endfor%}
        {% if page.has_next %}
        <a href="{% url 'product:list' current_type.id page.next_page_number %}?sort={{ sort }}">下一页></a>
        {% endif %}
    </div>
</div>
{%endblock list%}

FreshEveryDay/dailyfresh-master/dailyfresh-master/templates/products/p_base.html
{% extends 'base.html' %}
{% block header %}
    <div class="search_bar clearfix">
    <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
    <form method='get' action="/search/" target="_blank">
    <div class="search_con fl">
        <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
        <input type="submit" class="input_btn fr" name="" value="搜索">
    </div>
    </form>


    {% if user.is_authenticated %}
  <div class="guest_cart fr">
        <a href="/cart/" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
    </div>
        {% else %}
        <div class="guest_cart fr">
            <a href="{% url 'user:login' %}" class="cart_name fl">我的购物车</a>
        </div>
    {% endif %}
</div>
{% endblock %}
{% block main %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                {% for type in types %}
                <li><a href="{% url 'product:list' type.id 1 %}" class="{{ type.logo }}">{{ type.category_name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>

<div class="breadcrumb">
    <a href="/">全部分类</a>
    <span>></span>
    {% if product %}
    <a href="{% url 'product:list' product.type.id 1 %}">{{product.type.category_name}}</a>
    <span>></span>
    <a href="">商品详情</a>
        {% else %}
        <a href="{% url 'product:list' current_type.id 1 %}">{{current_type.category_name}}</a>
    {% endif %}
</div>


{% block detail %}
{% endblock detail%}

<div class="main_wrap clearfix">
    <div class="l_wrap fl clearfix">
        <div class="new_goods">
            <h3>新品推荐</h3>
            <ul>
                {%for np in new_products%}
                <li>
                    <a href="{% url 'product:detail' np.id %}"><img src="{{ np.image }}"></a>
                    <h4><a href="{% url 'product:detail' np.id %}">{{np.name}}</a></h4>
                    <div class="prize">￥{{np.price}}</div>
                </li>
                {%endfor%}
            </ul>
        </div>
    </div>
{% block list %}
{% endblock list %}
</div>
{% endblock main %}