FreshEveryDay/dailyfresh-master/dailyfresh-master/cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^addcart', views.add_cart, name='add_cart'),
    url(r'^updatecart', views.update_cart, name='update_cart'),
    url(r'^delete', views.delete, name='delete'),
    url(r'^$', views.cart, name='cart')
]

FreshEveryDay/dailyfresh-master/dailyfresh-master/dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from product.views import home
from dailyfresh.settings import BASE_DIR
from django.shortcuts import render


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^$', home, name='home'),
]

FreshEveryDay/dailyfresh-master/dailyfresh-master/order/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^commit/$', views.create_order, name='corder'),
    url(r'^payorder/$', views.payorder, name='payorder'),
    url(r'^orderpay/$', views.orderpay, name='orderpay'),
    url(r'^checkorder/$', views.checkorder, name='checkorder'),
]

FreshEveryDay/dailyfresh-master/dailyfresh-master/cart/models.py
from django.db import models

# Create your models here.

FreshEveryDay/dailyfresh-master/dailyfresh-master/cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django_redis import get_redis_connection
from django.contrib.auth.decorators import login_required
from product.models import ProductSKU


@login_required
def cart(request):
    user = request.user
    conn = get_redis_connection('default')
    cart_key = 'cart_%d' % user.id
    carts = conn.hgetall(cart_key)
    total_count = 0
    cart_products = []
    for sku_id, key in carts.items():
        total_count += int(key)
        p = ProductSKU.objects.get(id=sku_id)
        p.count = int(key)
        p.product_total_price = float(p.price)*int(key)
        cart_products.append(p)
    return render(request, 'cart/cart.html', {'carts': cart_products, 'total_count': total_count})


def add_cart(request):
    user = request.user
    if request.method == "POST":
        if not user.is_authenticated():
            return JsonResponse({'status': 0, 'msg': '您还没有登录'})
        sku_id = request.POST['sku_id']
        count = request.POST['count']
        print(sku_id, count)
        if not all([sku_id, count]):
            return JsonResponse({'status': 1, 'msg': '数据不完整'})
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'status': 2,'msg': '商品数目出错'})
        try:
            product = ProductSKU.objects.get(id=sku_id)
        except ProductSKU.DoesNotExist:
            return JsonResponse({'status': 3, 'msg': '商品不存在'})
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        try:
            db_count = conn.hget(cart_key, sku_id)
            db_count += count
        except Exception:
            db_count = count
        conn.hset(cart_key, sku_id, db_count)
        total_count = conn.hlen(cart_key)
        return JsonResponse({'status': 5, 'msg': '添加成功', 'total_count': total_count})


def update_cart(request):
    user = request.user
    if request.method == "POST":
        if not user.is_authenticated():
            return JsonResponse({'status': 0, 'msg': '您还没有登录'})
        sku_id = request.POST['sku_id']
        count = request.POST['count']
        print(sku_id, count)
        if not all([sku_id, count]):
            return JsonResponse({'status': 1, 'msg': '数据不完整'})
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'status': 2, 'msg': '商品数目出错'})
        try:
            product = ProductSKU.objects.get(id=sku_id)
        except ProductSKU.DoesNotExist:
            return JsonResponse({'status': 3, 'msg': '商品不存在'})
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        try:
            db_count = conn.hget(cart_key, sku_id)
            db_count += count
        except Exception:
            db_count = count
        if db_count>product.inventory:
            return JsonResponse({'status': 6, 'msg': '库存不足'})
        conn.hset(cart_key, sku_id, db_count)
        num = 0
        for value in conn.hgetall(cart_key).values():
            num += int(value)
        return JsonResponse({'status': 5, 'msg': '添加成功', 'total_count': db_count})


def delete(request):
    if request.method == "POST":
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'status': 0, 'msg': '您还没有登录'})
        sku_id = request.POST['sku_id']
        if not sku_id:
            return JsonResponse({'status': 1, 'msg': '商品为空'})
        try:
            sku_id = int(sku_id)
            product = ProductSKU.objects.get(id=sku_id)
        except ProductSKU.DoesNotExist:
            return JsonResponse({'status': 2, 'msg': '商品不存在'})
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        conn.hdel(cart_key, sku_id)
        count1 = 0
        for count in conn.hgetall(cart_key).values():
            count = int(count)
            count1 += count
        return JsonResponse({'status': 3, 'msg': '删除成功', 'count': count1})

FreshEveryDay/dailyfresh-master/dailyfresh-master/templates/cart/cart.html
{% extends 'base.html' %}
{% block header %}
    <div class="search_bar clearfix">
    <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
    <form method='get' action="/search/" target="_blank">
    <div class="search_con fl">
        <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
        <input type="submit" class="input_btn fr" name="" value="搜索">
    </div>
    </form>
</div>
{% endblock %}
{% block title %}
    购物车
{% endblock %}
{% block main %}
	<div class="total_count">全部商品<em class="total_count1">{{ total_count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
<form action="{% url 'order:payorder' %}" method="post">
    {%for cart in carts%}
	<ul class="cart_list_td clearfix" id="{{cart.id}}">
        {% csrf_token %}
		<li class="col01"><input type="checkbox" name="sku_id" value="{{cart.id}}" checked="" class="checkbox"></li>
		<li class="col02"><img src="{{cart.image}}"></li>
		<li class="col03">{{cart.name}}<br><em>{{cart.price}}元/{{cart.unite}}</em></li>
		<li class="col04">{{cart.unite}}</li>
		<li class="col05">{{cart.price}}</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" data-id="{{ cart.id }}">+</a>
				<input type="text" class="num_show fl" data-id="{{ cart.id }}" value="{{cart.count}}">
				<a href="javascript:;" class="minus fl" data-id="{{ cart.id }}">-</a>
			</div>
		</li>
		<li class="col07">{{cart.product_total_price}}</li>
		<li class="col08"><a id="delete" data-id="{{ cart.id }}" href="">删除</a></li>
		<!--class="del_good-->
	</ul>
	{%endfor%}

	<ul class="settlements">
{#		<li class="col01"><input type="checkbox" name="" checked="" id="checkToggle"></li>#}
		<li class="col01"><input type="checkbox" name="" checked="" id="checkToggle"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em id="sumtotal"></em><br>共计<b class="countGood">{{ total_count }}</b>件商品</li>
		<li class="col04"><input class="order" name="" type="submit" value="去结算"/></li>
	</ul>
</form>
{%endblock%}
{% block js%}
    <script>
        //计算总件数以及总价格
        function get_total_price(){
            total_price = 0
            total_count = 0
            $('.cart_list_td').find(':checked').parents('ul').each(function () {
                p_num = $(this).find('.num_show').val()
                p_price = $(this).find('.col07').text()
                total_count += parseInt(p_num)
                total_price += parseFloat(p_price)
            })
            $('.settlements').find('#sumtotal').text(total_price)
            $('.settlements').find('.countGood').text(total_count)
        }
        //当某个商品选中或者未选中时，更新当前页面的的状态
        $('.cart_list_td').find(':checkbox').change(function () {
            all_len = $('.cart_list_td').find(':checkbox').length
            check_len = $('.cart_list_td').find(':checked').length
            {#is_checkd = true#}
            if(all_len>check_len){
                $('.settlements').find(':checkbox').prop('checked', false)
            }
            else {
                $('.settlements').find(':checkbox').prop('checked', true)
            }
            get_total_price()
        });
        //设置全选/全不选checkbox
        $('.settlements').find(':checkbox').change(function () {
            is_checked = $(this).prop('checked')
            $('.cart_list_td').find(':checkbox').each(function () {
                $(this).prop('checked', is_checked)
            })
            get_total_price()
        });
        //购物车增加
        $('.add').click(function () {
            sku_id = $(this).attr('data-id')
            count = $(this).next().val()
            count = parseInt(count) + 1
            csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val()
            params = {sku_id, count, csrfmiddlewaretoken}
            // 设置ajax请求为同步方式
            $.ajaxSettings.async = false
            $.post('/cart/updatecart', params, function (data) {
            if(data.status == 5){
                $('.total_count1').text(data.total_count)
                error_response = false
                {#alert('successful')#}
            }
            else{
                alert(data.msg)
                return
            }

        })
            $.ajaxSettings.async = true
            if(error_response==false){
                $(this).next().val(count)
                price = $(this).parents('ul').find('.col05').text()
                total_p = parseFloat(price) * parseInt(count)
                $(this).parents('ul').find('.col07').text(total_p)
                if($(this).parents('ul').find(':checked')){
                    get_total_price()
                }
            }
        })
        //购物车商品减少
        $('.minus').click(function () {
            sku_id = $(this).attr('data-id')
            count = $(this).prev().val()
            count = parseInt(count) - 1
            if(count<=0){
                return
            }
            csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val()
            params = {sku_id, count, csrfmiddlewaretoken}
            $.ajaxSettings.async = false
            $.post('/cart/updatecart', params, function (data) {
            if(data.status == 5){
                $('.total_count1').text(data.total_count)
                error_response = false
                {#alert('successful')#}
            }
            else{
                alert(data.msg)
            }

        })
            $.ajaxSettings.async = true
            if(error_response==false){
                $(this).prev().val(count)
                price = $(this).parents('ul').find('.col05').text()
                total_p = parseFloat(price) * parseInt(count)
                $(this).parents('ul').find('.col07').text(total_p)
                if($(this).parents('ul').find(':checked')){
                    get_total_price()
                }
            }
        })
        //手动输入
        g_count = 0
        $('.num_show').focus(function () {
            g_count = $(this).val()
        })
        $('.num_show').blur(function () {
            sku_id = $(this).attr('data-id')
            count = $(this).val()
            if(parseInt(count<=0) || isNaN(count)){
                 //输入值无效
                $(this).val(g_count)
                return
            }
            csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val()
            params = {sku_id, count, csrfmiddlewaretoken}
            $.ajaxSettings.async = false
            $.post('/cart/updatecart', params, function (data) {
            if(data.status == 5){
                $('.total_count1').text(data.total_count)
                error_response = false
                {#alert('successful')#}
            }
            else{
                alert(data.msg)
            }

        })
            $.ajaxSettings.async = true
            if(error_response==false){
                $(this).val(count)
                price = $(this).parents('ul').find('.col05').text()
                total_p = parseFloat(price) * parseInt(count)
                $(this).parents('ul').find('.col07').text(total_p)
                if($(this).parents('ul').find(':checked')){
                    get_total_price()
                }
            }
        })
        //删除商品
        $('#delete').click(function () {
            sku_id = $(this).attr('data-id')
            csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val()
            params = {sku_id, csrfmiddlewaretoken}
            ul = $(this).parents('.cart_list_td')
            $.post('/cart/delete', params, function (data) {
                if(data.status==3){
                    $('.total_count1').text(data.count)
                 ul.remove()
                 if($(this).parents('ul').find(':checked')){
                     get_total_price()
                 }
                 {#alert('shanchuchenggong')#}
                }
                else{
                    alert(data.msg)
                }
            })
        })
        $(function () {
            get_total_price()
        })
    </script>
{% endblock %}